Server LLM: {
  GPU <-> Ollama
}

Server DATA: {
  ElasticStack: {
    Elasticsearch <-> Kibana
  }
  ElastiFlow -> ElasticStack.Elasticsearch
}

Server APP.Python <-> Server DATA.ElasticStack.Elasticsearch
Server APP.Python <-> Server LLM.Ollama

Router with NetFlow -> Server DATA.ElastiFlow: Netflow v9
